### ISSUE TITLE
Verdictdb on postgresql and concurrency

### ISSUE THREAD

**Issue by AdaZheng98** [verdict-project/verdict#389]
I couldn't find any information about concurrency in the documentation, is it supported? In my application, I have several clients selecting from the same database at the same time. How can I achieve this using verdictdb?

**Comment by pyongjoo** [comment]
Your database must support concurrent queries. If so, you can simply issue multiple queries concurrently using threads in your application.

FYI, some databases process queries one by one; then, of course, there is not much stuff we can do about it.
