### ISSUE TITLE
Where is the implementation of error estimation？

### ISSUE THREAD

**Issue by 01lin** [verdict-project/verdict#395]
See the error estimation based on variational sampling in the “verdict..” paper, but did not find the implementation and corresponding API interface in the code.  Why?
Thanks for your time.

**Comment by pyongjoo** [comment]
Please find the error estimation logic [here](https://github.com/verdict-project/verdict/blob/sigmod18/core/src/main/java/edu/umich/verdict/relation/ApproxAggregatedRelation.java#L95).

Since then, we have made much change to this repository to test different ideas.
